language: objective-c
os: osx
osx_image: xcode7.2
install:
  - gem install xcpretty
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

xcode_workspace: Example/ColorPicker.xcworkspace
xcode_scheme: ColorPicker

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild -workspace Example/ColorPicker.xcworkspace -scheme ColorPicker -configuration Release -destination "OS=9.2,name=iPhone 6S" -sdk "iphonesimulator9.2 -enableCodeCoverage YES build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
