language: objective-c
os: osx
osx_image: xcode7.2
install:
  - gem install xcpretty

xcode_workspace: Example/ColorPicker.xcworkspace
xcode_scheme: ColorPicker

script:
- xcodebuild -workspace Example/ColorPicker.xcworkspace -scheme ColorPicker -enableCodeCoverage YES clean build test | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
