# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

language: objective-c  #1
osx_image: xcode7.2 #2
xcode_workspace: Example/ColorPicker.xcworkspace #3
xcode_scheme: ColorPicker-Example #4
xcode_sdk: iphonesimulator9.2 #5
