# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

language: objective-c
osx_image: xcode7.2
install:
  - gem install xcpretty
# xcode_workspace: Example/ColorPicker.xcworkspace
# xcode_scheme: ColorPicker-Example
# xcode_sdk: iphonesimulator9.2
script:
  - xcodebuild test -workspace Example/ColorPicker.xcworkspace -scheme ColorPicker -sdk iphonesimulator9.2 -destination "OS=9.2,name=iPhone 6s" -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
